version: "3"

services:
  mongo-express:
   image: mongo-express
   depends_on:
     - 'mongo' 
   ports:
     - 8081:8081
   environment:
     ME_CONFIG_BASICAUTH_USERNAME: sol
     ME_CONFIG_BASICAUTH_PASSWORD: aqui sua senha
     ME_CONFIG_MONGODB_PORT: 20000
     ME_CONFIG_MONGODB_ADMINUSERNAME: root
     ME_CONFIG_MONGODB_ADMINPASSWORD: aqui sua senha

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sol-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dgeyqSjDj48sQsjtiu582n82
    ports:
      - "30000:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
